name: CI Workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up CWPL
      - name: Setup CWPL
        uses: actions/checkout@v1
        with:
          channel: stable
          use: 1.18.0


